//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int RollNumber { get; set; }
        public string StudentName { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Email { get; set; }
        public long PhoneNumber { get; set; }
        public string DoorNumber { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public int Pincode { get; set; }
        public double StudentFee { get; set; }
        public string Username { get; set; }
        public string StudentPassword { get; set; }
        public Nullable<int> CreatedAdmin { get; set; }
        public Nullable<int> CreatedTeacher { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
